### PR TITLE
Italian TL: minor fixes and update section translated

### PR DESCRIPTION
**Pull request by reinzanini**
Minor TL fixes and the update section was translated too. 
Also, about the "thank you to the following people" section, could you update it to include what TL they worked on? From `Reinzanini` to `Italiano: reinzanini` or something like that. Thanks for your work :)

### CODE REVIEW

**Comment by reinzanini** [comment]
And last thing, is there any way you could give me "write access" only to the `romfs/lang/it.json` file? PRing for every little thing doesn't sound too good to me, but you do you.

**Comment by tallbl0nde** [comment]
Thanks again! I've had a look and the only thing I could do is give you full access to the repo... which I'm not sure I want to do. To reduce the pull requests I could notify you just before each release as by then I'll have all the new text added (plus I'll need others to update their translations too anyway)

Regarding the thanks section I can do that!

**Comment by reinzanini** [comment]
> To reduce the pull requests I could notify you just before each release as by then I'll have all the new text added (plus I'll need others to update their translations too anyway)

Yeah, that would work too

**Comment by tallbl0nde** [comment]
@reinzanini All the new strings are ready to be translated - sorry for pinging you here (I don't know if there is a better way to do so on GitHub)

**Comment by evertonstz** [comment]
A somewhat good solution would be to make the lang folder a submodule to a new repository, in this new repository you could give full access to translators, the worst thing that can happen is a translator going crazy due to quarantine and deleting all the json files, but I'm sure other translator can replace the deleted files from local in case something like this happens so the damage would be minimal.

**Comment by evertonstz** [comment]
On the other hand if @reinzanini is not using github to make his pull requests, he could simply add the upstream to his local as explained [here](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork) so all he needs to do is merge upstream/master into his master before editing the json file, after that he can submit a pull request from command line, don't if that's the problem :)
But if most translators are actually working from the github editor I think using the submodule workaround would be for the best.

**Comment by tallbl0nde** [comment]
@evertonstz That's actually a great idea! I highly doubt anyone would do anything malicious anyway but I'm a lot happier with that method.

I won't do it just yet - I'll wait until I get translations from everyone for this update and then pull the files out into a submodule for future translations. :)

**Comment by reinzanini** [comment]
@tallbl0nde Sorry for the late answer! I've translated the file but... I'm not sure on what to do to merge it in your master. For the moment I'll just upload the it.json file (https://pastebin.com/dl/CGMZEpJ1), hope you don't mind. I really like the submodule idea btw. 
On a side note, I can't seem to be able to compile the .nro:

```
/home/rein/NX-Activity-Log/libs/Aether/source/utils/SDLHelper.cpp: In function 'bool SDLHelper::initSDL()':
/home/rein/NX-Activity-Log/libs/Aether/source/utils/SDLHelper.cpp:107:34: error: too few arguments to function 'Result plInitialize(PlServiceType)'
  107 |         Result rc = plInitialize();
      |                                  ^
In file included from /opt/devkitpro/libnx/include/switch.h:82,
                 from /home/rein/NX-Activity-Log/libs/Aether/include/utils/SDLHelper.hpp:7,
                 from /home/rein/NX-Activity-Log/libs/Aether/source/utils/SDLHelper.cpp:1:
/opt/devkitpro/libnx/include/switch/services/pl.h:36:8: note: declared here
   36 | Result plInitialize(PlServiceType service_type);
      |        ^~~~~~~~~~~~
make[2]: *** [/opt/devkitpro/devkitA64/base_rules:13: SDLHelper.o] Errore 1
make[2]: *** Attesa per i processi non terminati....
make[1]: *** [/home/rein/NX-Activity-Log/libs/Aether/Makefile:95: build] Errore 2
make[1]: uscita dalla directory «/home/rein/NX-Activity-Log/libs/Aether»
make: *** [Makefile:120: build] Errore 2
```

**Comment by tallbl0nde** [comment]
No problem! I can update the file.

With regards to compiling - are you using a newer version of libnx than 3.1.0? I've just done a clean build and it compiles fine. I've also found the commit that introduces PlServiceType was introduced 6 days ago, which is after the release of 3.1.0.

**Comment by reinzanini** [comment]
I'm using `libnx 3.1.0-1`, which should be the latest.

**Comment by tallbl0nde** [comment]
Somehow we must be getting different versions through dkp-pacman as I just reinstalled libnx and it indicated it was version `3.1.0-1`. I did another clean build and it compiled without issues again... I don't know why that would be the case though.

**Comment by reinzanini** [comment]
It seems the problem was that I was installing libnx from source, re-installing it from pacman solved that issue. But now this popped up instead:
```
/home/rein/NX-Activity-Log/source/utils/ThemeUtils.cpp:1:10: fatal error: simpleIniParser.hpp: No such file or directory
    1 | #include "simpleIniParser.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitA64/base_rules:14: ThemeUtils.o] Errore 1
make[1]: *** Attesa per i processi non terminati....
make: *** [Makefile:123: build] Errore 2
```

**Comment by tallbl0nde** [comment]
Ah that makes sense. Did you run `git submodule update --init` at all? I'm guessing the submodules just haven't been cloned. It's not meant to even try compiling if you haven't done so though.

**Comment by reinzanini** [comment]
I've done `git clone --recursive https://github.com/tallbl0nde/NX-Activity-Log.git` so that shouldn't be a problem.

**Comment by tallbl0nde** [comment]
I think I know what's up - the file is actually called `SimpleIniParser.hpp` and not `simpleIniParser.hpp`. So I must have some setting enabled to ignore the case which is why I haven't noticed. I'll push a commit to correct this.

**Comment by reinzanini** [comment]
That seems to be the issue. Copying `libs/SimpleIniParser/include/SimpleIniParser.hpp` to `libs/SimpleIniParser/include/simpleIniParser.hpp` solved and it compiled.

**Comment by tallbl0nde** [comment]
@evertonstz @reinzanini I've added both of you to the other repo, I guess we'll see how this works out!

**Pull request merged**
